receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: 'kong-gateway'
        scrape_interval: 5s
        static_configs:
        - targets: ['kong-data-plane:8100']
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
        - targets: ['otel-collector:8888']
processors:
  batch:
  resource:
    attributes:
      - action: upsert
        key: service.name
        value: kong-http-logs
exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "otel-collector:9090"
  otlphttp:
    endpoint: http://loki:3100/otlp
    encoding: json
service:
  telemetry:
    metrics:
      address: "otel-collector:8888"
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - resource
      exporters:
        - otlphttp
    metrics:
      receivers:
        - prometheus
      processors: []
      exporters:
        - prometheus
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - otlp/jaeger